export type DeviceSpec = {
  id: string;
  brand: "Pioneer" | "Denon";
  model: string;
  shortName: string;
  formats: string[];          // supported file extensions
  maxBitrateKbps: number;     // max lossy bitrate
  sampleRates: number[];      // supported sample rates (Hz)
  maxFileSizeMB: number;
  fat32Required: boolean;
  maxFolderDepth: number;
  maxFilesPerFolder: number;
  id3v2_4: boolean;           // supports ID3v2.4 tags
  flac: boolean;
  notes: string[];
};

export const DEVICES: DeviceSpec[] = [
  {
    id: "cdj-2000",
    brand: "Pioneer",
    model: "CDJ-2000",
    shortName: "CDJ-2000",
    formats: ["mp3", "aac", "wav", "aiff", "aif"],
    maxBitrateKbps: 320,
    sampleRates: [44100, 48000],
    maxFileSizeMB: 2048,
    fat32Required: true,
    maxFolderDepth: 8,
    maxFilesPerFolder: 999,
    id3v2_4: false,
    flac: false,
    notes: ["No FLAC support", "FAT32 only", "ID3v2.3 recommended", "rekordbox analysis required for waveforms"],
  },
  {
    id: "cdj-2000nxs",
    brand: "Pioneer",
    model: "CDJ-2000NXS",
    shortName: "CDJ-2000NXS",
    formats: ["mp3", "aac", "wav", "aiff", "aif"],
    maxBitrateKbps: 320,
    sampleRates: [44100, 48000],
    maxFileSizeMB: 2048,
    fat32Required: false,
    maxFolderDepth: 8,
    maxFilesPerFolder: 999,
    id3v2_4: false,
    flac: false,
    notes: ["No FLAC support", "FAT32 or exFAT", "ID3v2.3 recommended"],
  },
  {
    id: "cdj-2000nxs2",
    brand: "Pioneer",
    model: "CDJ-2000NXS2",
    shortName: "CDJ-2000NXS2",
    formats: ["mp3", "aac", "wav", "aiff", "aif", "flac"],
    maxBitrateKbps: 320,
    sampleRates: [44100, 48000, 88200, 96000],
    maxFileSizeMB: 4096,
    fat32Required: false,
    maxFolderDepth: 8,
    maxFilesPerFolder: 999,
    id3v2_4: true,
    flac: true,
    notes: ["FLAC up to 96kHz/24-bit", "FAT32 or exFAT"],
  },
  {
    id: "cdj-3000",
    brand: "Pioneer",
    model: "CDJ-3000",
    shortName: "CDJ-3000",
    formats: ["mp3", "aac", "wav", "aiff", "aif", "flac"],
    maxBitrateKbps: 320,
    sampleRates: [44100, 48000, 88200, 96000],
    maxFileSizeMB: 4096,
    fat32Required: false,
    maxFolderDepth: 8,
    maxFilesPerFolder: 999,
    id3v2_4: true,
    flac: true,
    notes: ["Full FLAC support", "rekordbox 6+ recommended"],
  },
  {
    id: "xdj-rx",
    brand: "Pioneer",
    model: "XDJ-RX",
    shortName: "XDJ-RX",
    formats: ["mp3", "aac", "wav", "aiff", "aif"],
    maxBitrateKbps: 320,
    sampleRates: [44100, 48000],
    maxFileSizeMB: 2048,
    fat32Required: true,
    maxFolderDepth: 8,
    maxFilesPerFolder: 999,
    id3v2_4: false,
    flac: false,
    notes: ["No FLAC support", "FAT32 required"],
  },
  {
    id: "xdj-rx2",
    brand: "Pioneer",
    model: "XDJ-RX2",
    shortName: "XDJ-RX2",
    formats: ["mp3", "aac", "wav", "aiff", "aif", "flac"],
    maxBitrateKbps: 320,
    sampleRates: [44100, 48000, 88200, 96000],
    maxFileSizeMB: 4096,
    fat32Required: false,
    maxFolderDepth: 8,
    maxFilesPerFolder: 999,
    id3v2_4: true,
    flac: true,
    notes: ["FAT32 or exFAT"],
  },
  {
    id: "xdj-rx3",
    brand: "Pioneer",
    model: "XDJ-RX3",
    shortName: "XDJ-RX3",
    formats: ["mp3", "aac", "wav", "aiff", "aif", "flac"],
    maxBitrateKbps: 320,
    sampleRates: [44100, 48000, 88200, 96000],
    maxFileSizeMB: 4096,
    fat32Required: false,
    maxFolderDepth: 8,
    maxFilesPerFolder: 999,
    id3v2_4: true,
    flac: true,
    notes: ["FAT32 or exFAT", "rekordbox 6+ recommended"],
  },
  {
    id: "xdj-1000mk2",
    brand: "Pioneer",
    model: "XDJ-1000MK2",
    shortName: "XDJ-1000MK2",
    formats: ["mp3", "aac", "wav", "aiff", "aif", "flac"],
    maxBitrateKbps: 320,
    sampleRates: [44100, 48000, 88200, 96000],
    maxFileSizeMB: 4096,
    fat32Required: false,
    maxFolderDepth: 8,
    maxFilesPerFolder: 999,
    id3v2_4: true,
    flac: true,
    notes: ["FAT32 or exFAT"],
  },
  {
    id: "denon-sc6000",
    brand: "Denon",
    model: "SC6000 / SC6000M",
    shortName: "SC6000",
    formats: ["mp3", "aac", "wav", "aiff", "aif", "flac", "ogg", "m4a"],
    maxBitrateKbps: 320,
    sampleRates: [44100, 48000, 88200, 96000],
    maxFileSizeMB: 4096,
    fat32Required: false,
    maxFolderDepth: 8,
    maxFilesPerFolder: 9999,
    id3v2_4: true,
    flac: true,
    notes: ["Broadest format support", "FAT32 or exFAT or NTFS", "Engine DJ software recommended"],
  },
  {
    id: "denon-sc5000",
    brand: "Denon",
    model: "SC5000 / SC5000M",
    shortName: "SC5000",
    formats: ["mp3", "aac", "wav", "aiff", "aif", "flac", "ogg", "m4a"],
    maxBitrateKbps: 320,
    sampleRates: [44100, 48000, 88200, 96000],
    maxFileSizeMB: 4096,
    fat32Required: false,
    maxFolderDepth: 8,
    maxFilesPerFolder: 9999,
    id3v2_4: true,
    flac: true,
    notes: ["FAT32, exFAT, or NTFS supported", "Engine DJ recommended"],
  },
  {
    id: "denon-prime4",
    brand: "Denon",
    model: "Prime 4 / Prime 2",
    shortName: "Prime 4",
    formats: ["mp3", "aac", "wav", "aiff", "aif", "flac", "ogg", "m4a"],
    maxBitrateKbps: 320,
    sampleRates: [44100, 48000, 88200, 96000],
    maxFileSizeMB: 4096,
    fat32Required: false,
    maxFolderDepth: 8,
    maxFilesPerFolder: 9999,
    id3v2_4: true,
    flac: true,
    notes: ["All-in-one standalone unit", "Internal drive or USB"],
  },
];

export function getDevice(id: string): DeviceSpec | undefined {
  return DEVICES.find((d) => d.id === id);
}
